server:
  port: 8080
db:
  port: 3306
  name: ticket_show_db
  endpoint: localhost
  username: root
  password: Sang@1991

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.endpoint}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

twilio:
  account:
    sid: AC88f2680ca4cf88da74c71eeb86967dd5
  auth:
    token: ea4f60c4d0b766b4c3ffadf9deff563e
  phone:
    number: +12565107871

#url:
#  redirect:
#    path: ${domain.path}
#domain:
#  path: http://localhost:3000/
