server:
  port: ${PORT}
db:
  port: ${DB_PORT}
  name: ${DB_NAME}
  endpoint: ${DB_ENDPOINT}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.endpoint}:${db.port}/${db.name}?useSSL=true
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      redirectUrl: ${GOOGLE_REDIRECT_URL}
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

upload:
  path: /home/site/wwwroot/uploads

app:
  frontend:
    url: ${FRONTEND_URL}
  cors:
    allowed-origins:
      - ${FRONTEND_URL}
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - X-Requested-With
    allow-credentials: true
    max-age: 3600