server:
  port: 8080
db:
  port: 3306
  name: ticket_show_db
  endpoint: localhost
  username: root
  password: 1234

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.endpoint}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 675ddba60da419
    password: 3354d34cda867d
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: ${JWT_SECRET:OVATION_SECRET_KEY_MUST_BE_LONGER_THAN_32_CHARACTERS}
  expiration: 86400000

stripe:
  secret:
    key: sk_test_51NxFXHLLGRqyYpieHwW76KV4ucGDTWQ7gibPokAXSYKwIuXuQdMEdNITA3XMFJhKQqG4pfUAY4I1TvhbAD02q4Y500Du2KvhR6
  webhook:
    secret: whsec_DTIsy7YtPPwMLT6tWjDlaA5EPmP12I9A

upload:
  path: ./uploads
#  mvc:
#    static-path-pattern: /images/**
#  web:
#    resources:
#      static-locations: classpath:/static/images/
#url:
#  redirect:
#    path: ${domain.path}
#domain:
#  path: http://localhost:3000/
