name: Deploy App to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Upload Artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ticketshow_backend-0.0.1-SNAPSHOT
          path: ${{ github.workspace }}/target/*.jar
  deploy:
    runs-on: ubuntu-lastest
    needs: build
    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ticketshow_backend-0.0.1-SNAPSHOT
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ticketshow_backend-0.0.1-SNAPSHOT
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: '*.jar'